-- One row per charge attempt for an order.
CREATE TABLE charges (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT       NOT NULL,
    amount_paise   BIGINT       NOT NULL,
    card_number    VARCHAR(19)  NOT NULL,
    merchant_id    VARCHAR(32)  NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    bank_reference VARCHAR(40),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- An order is charged at most once. A repeated request finds the first charge.
    CONSTRAINT uq_charges_order_id UNIQUE (order_id)
);
